### ISSUE TITLE
Which specific TOML 1.0.0 release candidate is supported?

### ISSUE THREAD

**Issue by marzer** [JuliaLang/TOML.jl#15]
TOML isn't at `1.0.0` yet. It's still in the Release Candidate cycle, of which there have been three. This project advertises support for `1.0.0`, but which RC?

Consider updating the project's README to specify the specific RC version.

**Comment by KristofferC** [comment]
1.0 is now released. Things that are not according to the 1.0  spec should be considered as bugs.
