### ISSUE TITLE
Docs example for writing to file doesn't actually give an example to write to file

### ISSUE THREAD

**Issue by anandijain** [JuliaLang/TOML.jl#18]
[This](https://docs.julialang.org/en/v1.7-dev/stdlib/TOML/#Exporting-data-to-TOML-file) should probably have an example like 

```julia 
open("myfile.toml", "w") do io
           TOML.print(io, dict)
end
```

**Comment by KristofferC** [comment]
The docstring makes it obvious (https://docs.julialang.org/en/v1.7-dev/stdlib/TOML/#TOML.print) but adding something in the example makes sense, yes.

**Comment by jaakkor2** [comment]
The header in https://docs.julialang.org/en/v1.7-dev/stdlib/TOML/#Exporting-data-to-TOML-file explicitely suggests about `Exporting-data-to-TOML-file`.

Now the example has an unused line
```
fname = tempname();
```
