### ISSUE TITLE
TOML printing of strings escaped with `\xnn` doesn't round trip

### ISSUE THREAD

**Issue by c42f** [JuliaLang/TOML.jl#22]
I was playing with storing binary data in certian TOML strings, and discovered TOML.jl doesn't escape these on output in a way which can be read back in again using TOML.parse.  For example:

```julia
julia> TOML.print(Dict("x"=>"\x01"))
x = "\x01"

julia> TOML.parse(sprint(TOML.print, Dict("x"=>"\x01")))
ERROR: TOML Parser error:
none:1:7 error: invalid escape character
  x = "\x01"
        ^    
Stacktrace:
 [1] parse
   @ ./toml_parser.jl:441 [inlined]
 [2] parse(str::String)
   @ TOML /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/TOML/src/TOML.jl:71
 [3] top-level scope
   @ REPL[80]:1
```

It seems that `TOML.print` should be escaping bytes as unicode codepoints with `\uXXXX`, or `\UXXXXXXXX`, instead (https://toml.io/en/v1.0.0#string). The parser works for this.

```
julia> TOML.parse("x = \"\\u0001\"")
Dict{String, Any} with 1 entry:
  "x" => "\x01"
```

**Comment by KristofferC** [comment]
> I was playing with storing binary data in certain TOML strings

But TOML strings need to have valid Unicode scalar values so wouldn't that limit you?

**Comment by KristofferC** [comment]
Regarding the bug, yes we should check `Unicode.iscntrl` and escape those.

**Comment by c42f** [comment]
> But TOML strings need to have valid Unicode scalar values so wouldn't that limit you?

Yeah, I'm using base64 to avoid those kind of problems. Trying the non-encoded form was a short experiment I quickly abandoned :)
