### ISSUE TITLE
How to convert TOML file into a Structure and vice versa?

### ISSUE THREAD

**Issue by joseph-pollacco** [JuliaLang/TOML.jl#31]
Hi I have a large SoilWater-ToolBox model and I have got all the input , [Parameters](https://github.com/manaakiwhenua/SoilWater_ToolBox/blob/master/src/Param.jl), as a **mutable struct**. In order to create a package I will need to read the parameters outside the model as recommended in previous post as a TOML.

> So the question is how to convert the structure into **TOML**?
>  Then how to read **TOML** file into a **structure**?

**I will be delighted if one can provide me guidance how to perform this task by using the proposed  simple structure:**

```
mutable struct OPTION
   transpiration
   soil 
end

   mutable struct TRANSPIRATION
      Evaporation :: Bool
      Transpiration :: Bool
   end

   mutable struct SOIL
      Topsoil :: Bool
      Macropore :: Bool
   end

Evaporation = true
Transpiration = false
   transpiration = TRANSPIRATION(Evaporation, Transpiration)

   Topsoil = true
   Macropore = false
soil = SOIL(Topsoil, Macropore)

option = OPTION(transpiration, soil)
```

**Comment by KristofferC** [comment]
The data types supported by TOML is documented here https://julialang.github.io/TOML.jl/dev/#TOML.print. You would need to convert your struct to those data types to write the TOML file and then back from them to create the struct.

**Comment by joseph-pollacco** [comment]
Dear Kristoffer,

Thanks for responding. It is not as obvious for scientist and I will be more than delighted if you can provide some clarity for this simple example that will be ever so kind of you:

THE TOML file
[evapotranspiration]
   Evaporation = true
   Transpiration = false


MY CODE
mutable struct OPTION
   transpiration
   soil
end

using TOML, StructTypes
function TOML_TEST()
   PathHome = @__DIR__

   Path = PathHome *  "/Toml.toml"
   TomlParse = TOML.tryparsefile(Path)


   Evaporation = TomlParse["evapotranspiration"]["Evaporation"]
   Transpiration = TomlParse["evapotranspiration"]["Transpiration"]

   evapotranspiration = EVAPOTRANSPIRATION(Evaporation, Transpiration)

   println(evapotranspiration.Evaporation)

 end

**Comment by KristofferC** [comment]
Just create your struct from the data:

```

   Evaporation = TomlParse["evapotranspiration"]["Evaporation"]
   Transpiration = TomlParse["evapotranspiration"]["Transpiration"]

   OPTION(evaporation, transpiration)
```

or something. StructTypes is not really related to this package.

**Comment by StefanKarpinski** [comment]
In other words you call `TOML.parsefile` to parse the file, which gives you a Dict (or other TOML data structure) and then you can write code to convert the contents of that Dict into whatever data structures you want.

**Comment by joseph-pollacco** [comment]
Thanks Stefan,

We have now resolved the issue,

Joseph
