### ISSUE TITLE
Reduce the number of test files

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/TOML.jl#41]
This repo contains a large number of very small test files. These are useful but having so many files bloats e.g. the Julia installation since the tests are shipped. It would probably be better to ship them via a tar-ball and then untar them to some tmp directory when the tests run.

**Comment by Jay-sanjay** [comment]
Sir,I wanted to work on it . Is it a good first issue for me to work on it

**Comment by KristofferC** [comment]
This was fixed in https://github.com/JuliaLang/TOML.jl/commit/38ee3e0da9d8feafd5990307dd41d5560aa7d0bf. Sorry, I should have closed this issue.

**Comment by Jay-sanjay** [comment]
yeah ,no problem sir . It would be great if you add the tags for the good first issues for this repo
